#!/usr/bin/env bash
# Script pour changer l'IP de localhost et de facebook.com

# Modifier le fichier /etc/hosts
sudo sed -i '/127.0.0.2 localhost/d' /etc/hosts
sudo sed -i '/8.8.8.8 facebook.com/d' /etc/hosts

# Ajouter les nouvelles résolutions DNS
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
