#!/usr/bin/env bash
# Modifier le fichier /etc/hosts pour redéfinir localhost et facebook.com

# Vérifier si l'utilisateur a les permissions nécessaires pour modifier /etc/hosts
if [ -w /etc/hosts ]; then
  # Modifier l'entrée pour localhost
  sed -i '/127.0.0.2/d' /etc/hosts
  echo "127.0.0.2 localhost" >> /etc/hosts
  
  # Modifier l'entrée pour facebook.com
  sed -i '/8.8.8.8/d' /etc/hosts
  echo "8.8.8.8 facebook.com" >> /etc/hosts
else
  echo "Erreur: Vous n'avez pas les permissions pour modifier /etc/hosts"
fi
